server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: org.SpringCloudDemo.vo
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db8001?serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
#security:
#  basic:
#    enabled: true
#  user:
#    name: lans
#    password: hello
#    role:
#    - USER
#  sessions: stateless