server:
  port: 7001
spring:
  application:
    name: EurekaServer
eureka:
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 3000
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:hello@eureka7002.com:7002/eureka,http://eureka:hello@eureka7003.com:7003/eureka
      
security:
  basic:
    enabled: true
  user:
    name: eureka
    password: hello